message(getwd())
scGate_models_DB_geneset1 <- suppressMessages(suppressWarnings(custom_db_scGATE("../custom_db/GeneSet1")))
scGate_models_DB_geneset2 <- suppressMessages(suppressWarnings(custom_db_scGATE("../custom_db/GeneSet2")))
scGate_models_DB_geneset3 <- suppressMessages(suppressWarnings(custom_db_scGATE("../custom_db/GeneSet3")))
scGate_models_DB_geneset4 <- suppressMessages(suppressWarnings(custom_db_scGATE("../custom_db/GeneSet4")))
scGate_models_DB_geneset5 <- suppressMessages(suppressWarnings(custom_db_scGATE("../custom_db/GeneSet5")))
scGate_models_DB_geneset6 <- suppressMessages(suppressWarnings(custom_db_scGATE("../custom_db/GeneSet6")))
scGate_models_DB_geneset7 <- suppressMessages(suppressWarnings(custom_db_scGATE("../custom_db/GeneSet7")))
scGate_models_DB_geneset8 <- suppressMessages(suppressWarnings(custom_db_scGATE("../custom_db/GeneSet8")))
scGate_models_DB_geneset9 <- suppressMessages(suppressWarnings(custom_db_scGATE("../custom_db/GeneSet9")))
